#lang s-exp phc-adt/declarations
(remembered! tagged-structure (tg a b))
(remembered! tagged-structure (tg a c))
(remembered! tagged-structure (t0))
(remembered! tagged-structure (City citizens name streets))
(remembered! tagged-structure (Street houses name))
(remembered! tagged-structure (House owner))
(remembered! tagged-structure (Person name))
(remembered! tagged-structure (node-incompleteᵢ citizens name streets))
(remembered! tagged-structure (node-incompleteᵢ houses name))
(remembered! tagged-structure (node-incompleteᵢ owner))
(remembered! tagged-structure (node-incompleteᵢ name))
(remembered! tagged-structure (| City-incomplete| citizens name streets))
(remembered! tagged-structure (| Street-incomplete| houses name))
(remembered! tagged-structure (| House-incomplete| owner))
(remembered! tagged-structure (| Person-incomplete| name))
(remembered! tagged-structure (City name))
