language: c

# Based from: https://github.com/greghendershott/travis-racket

# Optional: Remove to use Travis CI's older infrastructure.
sudo: false

env:
  global:
    # Supply a global RACKET_DIR environment variable. This is where
    # Racket will be installed. A good idea is to use ~/racket because
    # that doesn't require sudo to install and is therefore compatible
    # with Travis CI's newer container infrastructure.
    - RACKET_DIR=~/racket
  matrix:
    # Supply at least one RACKET_VERSION environment variable. This is
    # used by the install-racket.sh script (run at before_install,
    # below) to select the version of Racket to download and install.
    #
    # Supply more than one RACKET_VERSION (as in the example below) to
    # create a Travis-CI build matrix to test against multiple Racket
    # versions.
    - RACKET_VERSION=6.8
    - RACKET_VERSION=HEAD

matrix:
  allow_failures:
#   - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
- git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
- cat ~/travis-racket/install-racket.sh | bash # pipe to bash not sh!
- export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

install:
 - raco pkg install -j 2 --deps search-auto

before_script:

# Here supply steps such as raco make, raco test, etc.  You can run
# `raco pkg install --deps search-auto` to install any required
# packages without it getting stuck on a confirmation prompt.
script:
 - raco test -p subtemplate
 - raco setup --check-pkg-deps --pkgs subtemplate
 - raco pkg install doc-coverage
 #- raco doc-coverage -s 'pattern-expander\?|pattern-expander|prop:pattern-expander|syntax-local-syntax-parse-pattern-introduce|\.\.\.\+|attribute|boolean|char|character|define-conventions|define-eh-alternative-set|define-literal-set|define-splicing-syntax-class|define-syntax-class|define/syntax-parse|exact-integer|exact-nonnegative-integer|exact-positive-integer|expr|expr/c|id|identifier|integer|kernel-literals|keyword|literal-set->predicate|nat|number|pattern|static|str|syntax-parse|syntax-parser|this-syntax|~!|~and|~between|~bind|~commit|~datum|~delimit-cut|~describe|~do|~fail|~literal|~not|~once|~optional|~or|~parse|~peek|~peek-not|~post|~rest|~seq|~var|datum-case|define/with-syntax|syntax-case|syntax-case\*|with-datum|with-syntax' subtemplate
 - raco doc-coverage subtemplate/light
 #- raco pkg install --deps search-auto cover cover-codecov
 #- raco cover -b -f codecov -d $TRAVIS_BUILD_DIR/coverage .

after_success:
